"""empty message

Revision ID: 526e9833793a
Revises: 30bbfa6810a3
Create Date: 2022-12-04 18:35:31.489392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526e9833793a'
down_revision = '30bbfa6810a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_tags')
    # ### end Alembic commands ###
